[package]
name = "html-image-inline-base64"
description = "Reads an html file and inlines all the images with base64"
version = "0.1.0"
authors = ["EdJoPaTo <html-image-inline-base64-rust@edjopato.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image-base64-wasm = "0.6"
regex = "1"

[dependencies.clap]
version = "2"
features = ["wrap_help"]
